-- Ejecutá en Supabase → SQL Editor si ya tenés las tablas creadas

ALTER TABLE sponsors ADD COLUMN IF NOT EXISTS moneda TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE inscripciones ADD COLUMN IF NOT EXISTS moneda TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE gastos ADD COLUMN IF NOT EXISTS moneda TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE escenarios ADD COLUMN IF NOT EXISTS moneda TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE event_config ADD COLUMN IF NOT EXISTS break_even_moneda TEXT NOT NULL DEFAULT 'USD';
