ALTER TABLE sponsors ADD COLUMN IF NOT EXISTS segmento TEXT DEFAULT '';
ALTER TABLE sponsors ADD COLUMN IF NOT EXISTS prioridad TEXT DEFAULT '';
ALTER TABLE sponsors ADD COLUMN IF NOT EXISTS region TEXT DEFAULT '';
